apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydply
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
    spec:
      containers:
      - name: myc
        image: nginx
        ports:
        - containerPort: 80
