kind: Pod
apiVersion: v1
metadata: #name of po
  name: testpod
spec:
  containers:
    - name: c1
      image: ubuntu
      command:
        ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 5; done"]
    - name: c2
      image: ubuntu
      command:
        ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 5; done"]
