# Kubectl scale --replicas=8 rc -l myname=Surekha // to scale pod 
# Kubectl scale --replicas=3 rc -l myname=Surekha // to scale down pod 
# Kubectl delete -f myrc.yml
#kubectl  api-resources
kind: ReplicaSet # object kind RC
apiVersion: apps/v1
metadata:
  name: myrset #name of object
spec:
  replicas: 3 # how many pods need to create
  selector: # which pod to watch/belong to rc
    myname: Surekha # much match the label

  template: # what will be inside pod that we defind on template
    metadata:
      name: rspod # name of pof
      labels: # label on pof
        myname: Surekha
    spec: # what will be inside pod / contaier inside pof
      containers:
        - name: cnginx
          image: nginx
