---
# ansible-playbook webserver.yaml -K 
- name: "Install docker and maven with roles"
  hosts: all
  become: true
  roles: 
    - webserver # same directry if roles present
    - role: '/home/roles/webserver' # if roles keept in other location

    # - comman
    # - user_confi



- name: "Install php with roles"
  hosts: all
  become: true
  roles: 
    - php